-- WastePlanner — the WMP intro follows the scope selected in §1.1 (2026-09-17).
--
-- WHY
-- INTRO_1 ends "…generated by the development during {phase}". {phase} is now
-- read from §1.1: tick "Construction and demolition (C&D) waste" into scope
-- and it prints "construction, demolition and operation". Green Star gets its
-- own sentence, shown only when "Green Star compliance" is ticked into scope
-- (snippet condition `greenstar` — the same mechanism as `chutes` etc.).
--
-- WHAT THIS DOES (idempotent)
-- * Adds INTRO_2 to the live library if it is not there, conditioned on
--   greenstar, right after INTRO_1.
-- * Gives INTRO_1 its full stop where the body still ends in "{phase}".
-- Nothing else changes; the seed bundled in index.html carries the same rows
-- for the offline fallback.

insert into public.wmp_content (tag, grp, body, style, enabled, cond, sort)
select 'INTRO_2', '1. Introduction',
       'This WMP also documents the waste management measures relied upon for Green Star Buildings Credit 05 (Responsible Resource Management).',
       'p', true, 'greenstar',
       coalesce((select sort from public.wmp_content where tag = 'INTRO_1'), 0) + 1
where not exists (select 1 from public.wmp_content where tag = 'INTRO_2');

update public.wmp_content
   set body = body || '.'
 where tag = 'INTRO_1' and body like '%{phase}';
